import React from 'react';
import { Train, Ticket } from './types';

export const STATIONS = [
  "Dhaka", "Dhaka Cantt.", "Biman Bandar", "Chattogram", "Sylhet", "Rajshahi",
  "Khulna", "Rangpur", "Bogura", "Cumilla", "Mymensingh", "Brahmanbaria",
  "Feni", "Joypurhat", "Narsingdi", "Sreemangal", "Pabna", "Ishwardi"
];

export const TRAIN_CLASSES = [
  "AC_S", "AC_B", "SNIGDHA", "F_BERTH", "F_SEAT", "S_CHAIR", "SHOVON"
];

export const TRANSLATIONS = {
  en: {
    home: "Home",
    welcome: "Welcome",
    notif_welcome_title: "Welcome to Premium",
    notif_welcome_msg: "Experience the new way of train travel in Bangladesh.",
    track: "Live Tracking",
    history: "Tickets",
    profile: "Profile",
    from: "From",
    to: "To",
    date: "Journey Date",
    class: "Seat Class",
    search: "Search Trains",
    login: "Sign In",
    signup: "Register",
    logout: "Exit",
    personal_info: "Personal Data",
    payment_methods: "Wallets & Cards",
    security: "Security Center",
    help: "Concierge",
    share: "Share",
    install: "Install Premium",
    trips: "Trips",
    points: "Points",
    verified: "Verified",
    save: "Save Changes",
    name: "Full Name",
    phone: "Phone Number",
    email: "Email Address",
    nid: "NID Number",
    account: "Account",
    notifications: "Alerts",
    no_notifications: "No new alerts",
    active_trips: "Active Trips",
    upcoming: "Upcoming",
    stations: "Stations",
    select_station: "Select Station",
    select_class: "Select Class",
    find_train: "Find Train",
    intercity: "Intercity",
    no_trains: "No Services Found",
    adjust_filters: "Adjust your filters or try another date.",
    enter_train_number: "Enter Train Number",
    train_number_placeholder: "e.g. 701",
    live_satellite: "Live Satellite",
    on_time: "On Time",
    last_station: "Last Station",
    next_station: "Next Stop",
    exp_arrival: "Exp. Arrival",
    speed: "Speed",
    km_h: "KM/H",
    radar_standby: "Radar Standby",
    radar_desc: "Enter a valid train number to initialize real-time satellite tracking",
    view_details: "View Details",
    download_pass: "Download Pass",
    no_history: "No History Found",
    no_history_desc: "You haven't booked any tickets yet. Your next journey starts here.",
    passenger: "Passenger",
    seat: "Seat",
    fare: "Fare",
    securing_ticket: "Securing Ticket",
    please_wait_confirm: "Please wait while we confirm your journey.",
    booking_confirmed: "Booking Confirmed!",
    booking_success: "Successfully booked seats for ",
    checkout: "Checkout",
    base_fare: "Base Fare",
    platform_fee: "Platform Fee",
    confirm_book: "Confirm & Book",
    passenger_count: "Passenger",
    welcome_back: "Welcome Back",
    sign_in_desc: "Sign in to continue journey",
    mobile_email: "Mobile Number / Email",
    password: "Secret Password",
    forgot_password: "Forgot Password?",
    secure_access: "Secure Access",
    secured_by: "Secured by BR CyberShield",
    create_account: "Create Account",
    join_premium: "Join the premium travel club",
    agree_terms: "I agree to the Terms & Conditions",
    verify_nid: "Verify Identity",
    nid_desc: "National ID verification is mandatory for security",
    verify_now: "Verify Now",
    passenger_info: "Passenger Info",
    legal_name: "Legal Name",
    age: "Age",
    gender: "Gender",
    contact_whatsapp: "Contact WhatsApp",
    proceed_to_payment: "Proceed to Payment",
    male: "Male",
    female: "Female",
    other: "Other",
    travel_refined: "Travel Refined",
    premium_desc: "A premium journey through Bangladesh \n Elegant. Minimal. Fast.",
    guest_explorer: "Guest Explorer",
    reserved_seat: "Reserved Seat",
    contact_number: "Contact Number",
    traveller: "Traveller",
    selection: "Selection",
    tap_to_select: "Tap to Select",
    total_fare: "Total Fare",
    review_booking: "Review Booking",
    terms_info: "I agree to the Terms of Service and acknowledge the Railway Acts of 1890.",
    already_have_account: "Already have an account?",
    processing: "PROCESSING...",
    continue_verify: "CONTINUE TO VERIFY",
    terms_of_service: "Terms of Service",
    nid_verification: "NID Verification",
    nid_policy: "As per Bangladesh Railway policy, a valid NID is required for ticket issuance and identity verification.",
    verifying: "VERIFYING...",
    finish_setup: "FINISH SETUP",
    scan_upload: "Scan or Upload Photo",
    verified_by_ec: "Verified by Election Commission BD",
    payment: "Payment",
    total_amount: "Total Amount",
    tickets_for: "Tickets for",
    select_method: "Select Method",
    confirm_payment: "Confirm Payment",
    pay_securely: "Pay ৳{amount} Securely",
    debit_credit_card: "Debit/Credit Card",
    e_ticket_details: "E-Ticket Details"
  },
  bn: {
    home: "হোম",
    welcome: "স্বাগতম",
    track: "লাইভ ট্র্যাকিং",
    history: "টিকিটসমূহ",
    profile: "প্রোফাইল",
    from: "হতে",
    to: "গন্তব্য",
    date: "ভ্রমণের তারিখ",
    class: "আসন বিভাগ",
    search: "ট্রেন খুঁজুন",
    login: "লগইন",
    signup: "নিবন্ধন",
    logout: "প্রস্থান",
    personal_info: "ব্যক্তিগত তথ্য",
    payment_methods: "ওয়ালেট ও কার্ড",
    security: "নিরাপত্তা",
    help: "সহায়তা",
    share: "শেয়ার",
    install: "অ্যাপ ইনস্টল",
    trips: "ভ্রমণ",
    points: "পয়েন্ট",
    verified: "যাচাইকৃত",
    save: "পরিবর্তন সংরক্ষণ",
    name: "নাম",
    phone: "ফোন নম্বর",
    email: "ইমেইল অ্যাড্রেস",
    nid: "এনআইডি",
    account: "অ্যাকাউন্ট",
    notifications: "নোটিফিকেশনস",
    no_notifications: "কোন নোটিফিকেশন নেই",
    active_trips: "সক্রিয় ভ্রমণ",
    upcoming: "আসন্ন",
    stations: "স্টেশন",
    select_station: "স্টেশন নির্বাচন করুন",
    select_class: "শ্রেণী নির্বাচন করুন",
    find_train: "ট্রেন খুঁজুন",
    intercity: "আন্তঃনগর",
    no_trains: "কোন সার্ভিস পাওয়া যায়নি",
    adjust_filters: "অনুগ্রহ করে আপনার ফিল্টার পরিবর্তন করুন।",
    enter_train_number: "ট্রেন নম্বর লিখুন",
    train_number_placeholder: "উদাঃ ৭০১",
    live_satellite: "লাইভ স্যাটেলাইট",
    on_time: "সঠিক সময়",
    last_station: "শেষ স্টেশন",
    next_station: "পরবর্তী স্টপেজ",
    exp_arrival: "সম্ভাব্য আগমন",
    speed: "গতি",
    km_h: "কিমি/ঘণ্টা",
    radar_standby: "রাডার স্ট্যান্ডবাই",
    radar_desc: "রিয়েল-টাইম স্যাটেলাইট ট্র্যাকিং শুরু করতে একটি সঠিক ট্রেন নম্বর দিন",
    view_details: "বিস্তারিত দেখুন",
    download_pass: "পাশ ডাউনলোড",
    no_history: "কোন ইতিহাস পাওয়া যায়নি",
    no_history_desc: "আপনি এখনো কোন টিকিট বুক করেননি। আপনার পরবর্তী যাত্রা শুরু হোক এখান থেকেই।",
    passenger: "যাত্রী",
    seat: "আসন",
    fare: "ভাড়া",
    securing_ticket: "টিকিট নিশ্চিত করা হচ্ছে",
    please_wait_confirm: "অনুগ্রহ করে অপেক্ষা করুন, আপনার টিকিট নিশ্চিত হচ্ছে।",
    booking_confirmed: "বুকিং নিশ্চিত হয়েছে!",
    booking_success: "ভ্রমণ নিশ্চিত করা হয়েছে: ",
    checkout: "চেকআউট",
    base_fare: "টিকিট ভাড়া",
    platform_fee: "প্ল্যাটফর্ম চার্জ",
    confirm_book: "নিশ্চিত করুন",
    passenger_count: "যাত্রী",
    welcome_back: "আবার স্বাগতম",
    sign_in_desc: "ভ্রমণ চালিয়ে যেতে সাইন ইন করুন",
    mobile_email: "মোবাইল নম্বর / ইমেল",
    password: "পাসওয়ার্ড",
    forgot_password: "পাসওয়ার্ড ভুলে গেছেন?",
    secure_access: "লগইন করুন",
    secured_by: "সুরক্ষিত থাকছেন বিআর সাইবার-শিল্ডের মাধ্যমে",
    create_account: "অ্যাকাউন্ট তৈরি করুন",
    join_premium: "প্রিমিয়াম ট্রাভেল ক্লাবে যোগ দিন",
    agree_terms: "আমি শর্তাবলীতে রাজি",
    verify_nid: "পরিচয় নিশ্চিত করুন",
    nid_desc: "নিরাপত্তার জন্য জাতীয় পরিচয়পত্র যাচাই বাধ্যতামূলক",
    verify_now: "এখনই যাচাই করুন",
    passenger_info: "যাত্রীর তথ্য",
    details_for: "তথ্য প্রদান করুন",
    travellers: "জন যাত্রীর জন্য",
    legal_name: "পূর্ণ নাম",
    age: "বয়স",
    gender: "লিঙ্গ",
    contact_whatsapp: "যোগাযোগ (হোয়াটসঅ্যাপ)",
    proceed_to_payment: "পেমেন্টে এগিয়ে যান",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    travel_refined: "যাত্রা হোক অভিজাত",
    premium_desc: "বাংলাদেশের প্রথম প্রিমিয়াম ট্রেন ভ্রমণ অভিজ্ঞতা \n মার্জিত। ন্যূনতম। দ্রুত।",
    guest_explorer: "গেস্ট হিসেবে দেখুন",
    reserved_seat: "সংরক্ষিত আসন",
    selection: "নির্বাচন",
    tap_to_select: "নির্বাচন করুন",
    total_fare: "মোট ভাড়া",
    review_booking: "বুকিং নিশ্চিত করুন",
    terms_info: "আমি সেবার শর্তাবলীতে সম্মত এবং ১৮৯০ সালের রেলওয়ে আইন মেনে চলছি।",
    already_have_account: "আপনার কি অ্যাকাউন্ট আছে?",
    processing: "প্রক্রিয়াকরণ হচ্ছে...",
    continue_verify: "যাচাইয়ে অগ্রসর হোন",
    terms_of_service: "সেবার শর্তাবলী",
    nid_verification: "এনআইডি যাচাইকরণ",
    nid_policy: "বাংলাদেশ রেলওয়ের নীতিমালা অনুযায়ী, টিকিট ইস্যু এবং পরিচয় নিশ্চিতকরণের জন্য একটি বৈধ এনআইডি কার্ড থাকা বাধ্যতামূলক।",
    verifying: "যাচাই করা হচ্ছে...",
    finish_setup: "নিবন্ধন সম্পন্ন করুন",
    scan_upload: "ছবি স্ক্যান বা আপলোড করুন",
    verified_by_ec: "নির্বাচন কমিশন কর্তৃক যাচাইকৃত",
    payment: "পেমেন্ট",
    total_amount: "মোট টাকা",
    tickets_for: "টিকিট",
    select_method: "পেমেন্ট পদ্ধতি",
    confirm_payment: "পেমেন্ট সম্পন্ন করুন",
    pay_securely: "৳{amount} নিরাপদ পেমেন্ট",
    debit_credit_card: "ডেবিট/ক্রেডিট কার্ড",
    e_ticket_details: "ই-টিকিট বিবরণ"
  }
};

export const MOCK_TRAINS: Train[] = [
  {
    id: "1",
    name: "Suborno Express",
    number: "701",
    from: "Dhaka",
    to: "Chattogram",
    departureTime: "16:30",
    arrivalTime: "21:50",
    duration: "5h 20m",
    offDay: "Monday",
    classes: [
      { type: "SNIGDHA", fare: 725, available: 45 },
      { type: "S_CHAIR", fare: 380, available: 120 }
    ]
  },
  {
    id: "2",
    name: "Sonar Bangla Express",
    number: "787",
    from: "Dhaka",
    to: "Chattogram",
    departureTime: "07:00",
    arrivalTime: "12:15",
    duration: "5h 15m",
    offDay: "Wednesday",
    classes: [
      { type: "AC_S", fare: 1100, available: 10 },
      { type: "SNIGDHA", fare: 725, available: 32 },
      { type: "S_CHAIR", fare: 405, available: 85 }
    ]
  },
  {
    id: "3",
    name: "Parabat Express",
    number: "709",
    from: "Dhaka",
    to: "Sylhet",
    departureTime: "06:20",
    arrivalTime: "13:00",
    duration: "6h 40m",
    offDay: "Tuesday",
    classes: [
      { type: "AC_S", fare: 850, available: 8 },
      { type: "SNIGDHA", fare: 650, available: 20 },
      { type: "S_CHAIR", fare: 345, available: 150 }
    ]
  },
  {
    id: "4",
    name: "Silk City Express",
    number: "753",
    from: "Dhaka",
    to: "Rajshahi",
    departureTime: "14:40",
    arrivalTime: "20:35",
    duration: "5h 55m",
    offDay: "Sunday",
    classes: [
      { type: "AC_S", fare: 950, available: 15 },
      { type: "SNIGDHA", fare: 750, available: 25 },
      { type: "S_CHAIR", fare: 345, available: 60 }
    ]
  },
  {
    id: "5",
    name: "Mohanagar Express",
    number: "721",
    from: "Chattogram",
    to: "Dhaka",
    departureTime: "12:30",
    arrivalTime: "19:10",
    duration: "6h 40m",
    offDay: "Sunday",
    classes: [
      { type: "AC_S", fare: 950, available: 5 },
      { type: "SNIGDHA", fare: 650, available: 12 },
      { type: "S_CHAIR", fare: 345, available: 100 }
    ]
  }
];

export const MOCK_HISTORY: Ticket[] = [
  {
    id: "RS-99210",
    trainName: "Sonar Bangla Express",
    from: "Dhaka",
    to: "Chattogram",
    date: "2024-05-15",
    seats: ["C-12", "C-13"],
    totalAmount: 2220,
    status: 'confirmed',
    passengerName: "Tanvir Rahman",
    passengerPhone: "+8801700000000",
    passengers: [{ name: "Tanvir Rahman", phone: "+8801700000000", gender: "male", age: "25" }]
  },
  {
    id: "RS-88122",
    trainName: "Silk City Express",
    from: "Dhaka",
    to: "Rajshahi",
    date: "2024-04-10",
    seats: ["E-05"],
    totalAmount: 365,
    status: 'confirmed',
    passengerName: "Tanvir Rahman",
    passengerPhone: "+8801700000000",
    passengers: [{ name: "Tanvir Rahman", phone: "+8801700000000", gender: "male", age: "25" }]
  }
];
